spring.application.name=todo-sample

spring.datasource.driver-class-name=org.postgresql.Driver
# springアプリケーションでDB接続するときはjdbcを使う。
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_sample

spring.datasource.username=todo

spring.datasource.password=todo
# h2では有効だが、mysql,postgreの外部では必要。
spring.sql.init.mode=always
#package単位でログの出力を決める。
logging.level.com.example.todo_sample.repository=DEBUG
